openapi: 3.0.0
info:
  version: '2017-07-01'
  x-release: v4
  title: 'Amazon HealthLake #X Amz Target=HealthLake.CreateFHIRDatastore #X Amz Target=HealthLake.CreateFHIRDatastore #X Amz Target=HealthLake.CreateFHIRDatastore API'
  description: AWS HealthLake is a HIPAA eligibile service that allows customers to store, transform, query, and analyze their FHIR-formatted data in a consistent fashion in the cloud.
  x-logo:
    url: https://twitter.com/awscloud/profile_image?size=original
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: healthlake
  x-aws-signingName: healthlake
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/healthlake-2017-07-01.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://healthlake.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The HealthLake multi-region endpoint
- url: https://healthlake.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The HealthLake multi-region endpoint
- url: http://healthlake.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The HealthLake endpoint for China (Beijing) and China (Ningxia)
- url: https://healthlake.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The HealthLake endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: '#X Amz Target=HealthLake.CreateFHIRDatastore'
paths:
  /#X-Amz-Target=HealthLake.CreateFHIRDatastore:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    post:
      operationId: CreateFHIRDatastore
      description: Creates a data store that can ingest and export FHIR formatted data.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateFHIRDatastoreResponse'
        '480':
          description: ValidationException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationException'
        '481':
          description: ThrottlingException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThrottlingException'
        '482':
          description: AccessDeniedException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessDeniedException'
        '483':
          description: InternalServerException
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerException'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFHIRDatastoreRequest'
      parameters:
      - name: X-Amz-Target
        in: header
        required: true
        schema:
          type: string
          enum:
          - HealthLake.CreateFHIRDatastore
      summary: Amazon HealthLake Create FHIR Datastore
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - '#X Amz Target=HealthLake.CreateFHIRDatastore'
components:
  parameters:
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
  schemas:
    TagKey:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 1
      maxLength: 128
    IdentityProviderConfiguration:
      type: object
      required:
      - AuthorizationStrategy
      properties:
        AuthorizationStrategy:
          allOf:
          - $ref: '#/components/schemas/AuthorizationStrategy'
          - description: The authorization strategy that you selected when you created the data store.
        FineGrainedAuthorizationEnabled:
          allOf:
          - $ref: '#/components/schemas/Boolean'
          - description: If you enabled fine-grained authorization when you created the data store.
        Metadata:
          allOf:
          - $ref: '#/components/schemas/ConfigurationMetadata'
          - description: '<p>The JSON metadata elements that you want to use in your identity provider configuration. Required elements are listed based on the launch specification of the SMART application. For more information on all possible elements, see <a href="https://build.fhir.org/ig/HL7/smart-app-launch/conformance.html#metadata">Metadata</a> in SMART''s App Launch specification.</p> <p> <code>authorization_endpoint</code>: The URL to the OAuth2 authorization endpoint.</p> <p> <code>grant_types_supported</code>: An array of grant types that are supported at the token endpoint. You must provide at least one grant type option. Valid options are <code>authorization_code</code> and <code>client_credentials</code>.</p> <p> <code>token_endpoint</code>: The URL to the OAuth2 token endpoint.</p> <p> <code>capabilities</code>: An array of strings of the SMART capabilities that the authorization server supports.</p> <p> <code>code_challenge_methods_supported</code>: An array of strings of supported PKCE code challenge methods. You must include the <code>S256</code> method in the array of PKCE code challenge methods.</p>'
        IdpLambdaArn:
          allOf:
          - $ref: '#/components/schemas/LambdaArn'
          - description: The Amazon Resource Name (ARN) of the Lambda function that you want to use to decode the access token created by the authorization server.
      description: The identity provider configuration that you gave when the data store was created.
    DatastoreName:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-%@]*)$
      minLength: 1
      maxLength: 256
    PreloadDataConfig:
      type: object
      required:
      - PreloadDataType
      properties:
        PreloadDataType:
          allOf:
          - $ref: '#/components/schemas/PreloadDataType'
          - description: The type of preloaded data. Only Synthea preloaded data is supported.
      description: ' The input properties for the preloaded data store. Only data preloaded from Synthea is supported.'
    Tag:
      type: object
      required:
      - Key
      - Value
      properties:
        Key:
          allOf:
          - $ref: '#/components/schemas/TagKey'
          - description: ' The key portion of a tag. Tag keys are case sensitive. '
        Value:
          allOf:
          - $ref: '#/components/schemas/TagValue'
          - description: ' The value portion of a tag. Tag values are case sensitive. '
      description: ' A tag is a label consisting of a user-defined key and value. The form for tags is {"Key", "Value"} '
    EncryptionKeyID:
      type: string
      pattern: (arn:aws((-us-gov)|(-iso)|(-iso-b)|(-cn))?:kms:)?([a-z]{2}-[a-z]+(-[a-z]+)?-\d:)?(\d{12}:)?(((key/)?[a-zA-Z0-9-_]+)|(alias/[a-zA-Z0-9:/_-]+))
      minLength: 1
      maxLength: 400
    CreateFHIRDatastoreResponse:
      type: object
      required:
      - DatastoreId
      - DatastoreArn
      - DatastoreStatus
      - DatastoreEndpoint
      properties:
        DatastoreId:
          allOf:
          - $ref: '#/components/schemas/DatastoreId'
          - description: The AWS-generated data store id. This id is in the output from the initial data store creation call.
        DatastoreArn:
          allOf:
          - $ref: '#/components/schemas/DatastoreArn'
          - description: The data store ARN is generated during the creation of the data store and can be found in the output from the initial data store creation call.
        DatastoreStatus:
          allOf:
          - $ref: '#/components/schemas/DatastoreStatus'
          - description: The status of the FHIR data store.
        DatastoreEndpoint:
          allOf:
          - $ref: '#/components/schemas/BoundedLengthString'
          - description: The AWS endpoint for the created data store.
    DatastoreStatus:
      type: string
      enum:
      - CREATING
      - ACTIVE
      - DELETING
      - DELETED
    TagList:
      type: array
      items:
        $ref: '#/components/schemas/Tag'
      minItems: 0
      maxItems: 200
    BoundedLengthString:
      type: string
      pattern: '[\P{M}\p{M}]{1,5000}'
      minLength: 1
      maxLength: 5000
    ClientTokenString:
      type: string
      pattern: ^[a-zA-Z0-9-]+$
      minLength: 1
      maxLength: 64
    ConfigurationMetadata:
      type: string
    LambdaArn:
      type: string
      pattern: arn:aws:lambda:[a-z]{2}-[a-z]+-\d{1}:\d{12}:function:[a-zA-Z0-9\-_\.]+(:(\$LATEST|[a-zA-Z0-9\-_]+))?
      minLength: 49
      maxLength: 256
    AccessDeniedException: {}
    FHIRVersion:
      type: string
      enum:
      - R4
    CmkType:
      type: string
      enum:
      - CUSTOMER_MANAGED_KMS_KEY
      - AWS_OWNED_KMS_KEY
    Boolean:
      type: boolean
    DatastoreArn:
      type: string
      pattern: ^arn:aws((-us-gov)|(-iso)|(-iso-b)|(-cn))?:healthlake:[a-zA-Z0-9-]+:[0-9]{12}:datastore/.+?
    PreloadDataType:
      type: string
      enum:
      - SYNTHEA
    SseConfiguration:
      type: object
      required:
      - KmsEncryptionConfig
      properties:
        KmsEncryptionConfig:
          allOf:
          - $ref: '#/components/schemas/KmsEncryptionConfig'
          - description: ' The KMS encryption configuration used to provide details for data encryption. '
      description: ' The server-side encryption key configuration for a customer provided encryption key. '
    KmsEncryptionConfig:
      type: object
      required:
      - CmkType
      properties:
        CmkType:
          allOf:
          - $ref: '#/components/schemas/CmkType'
          - description: ' The type of customer-managed-key(CMK) used for encryption. The two types of supported CMKs are customer owned CMKs and AWS owned CMKs. '
        KmsKeyId:
          allOf:
          - $ref: '#/components/schemas/EncryptionKeyID'
          - description: ' The KMS encryption key id/alias used to encrypt the data store contents at rest. '
      description: ' The customer-managed-key(CMK) used when creating a data store. If a customer owned key is not specified, an AWS owned key will be used for encryption. '
    DatastoreId:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-%@]*)$
      minLength: 1
      maxLength: 32
    ThrottlingException: {}
    ValidationException: {}
    CreateFHIRDatastoreRequest:
      type: object
      required:
      - DatastoreTypeVersion
      title: CreateFHIRDatastoreRequest
      properties:
        DatastoreName:
          allOf:
          - $ref: '#/components/schemas/DatastoreName'
          - description: The user generated name for the data store.
        DatastoreTypeVersion:
          allOf:
          - $ref: '#/components/schemas/FHIRVersion'
          - description: The FHIR version of the data store. The only supported version is R4.
        SseConfiguration:
          allOf:
          - $ref: '#/components/schemas/SseConfiguration'
          - description: ' The server-side encryption key configuration for a customer provided encryption key specified for creating a data store. '
        PreloadDataConfig:
          allOf:
          - $ref: '#/components/schemas/PreloadDataConfig'
          - description: Optional parameter to preload data upon creation of the data store. Currently, the only supported preloaded data is synthetic data generated from Synthea.
        ClientToken:
          allOf:
          - $ref: '#/components/schemas/ClientTokenString'
          - description: Optional user provided token used for ensuring idempotency.
        Tags:
          allOf:
          - $ref: '#/components/schemas/TagList'
          - description: ' Resource tags that are applied to a data store when it is created. '
        IdentityProviderConfiguration:
          allOf:
          - $ref: '#/components/schemas/IdentityProviderConfiguration'
          - description: The configuration of the identity provider that you want to use for your data store.
    TagValue:
      type: string
      pattern: ^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$
      minLength: 0
      maxLength: 256
    InternalServerException: {}
    AuthorizationStrategy:
      type: string
      enum:
      - SMART_ON_FHIR_V1
      - AWS_AUTH
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/healthlake/
x-hasEquivalentPaths: true
